### ISSUE TITLE
how could i  get user's account name in python

### ISSUE THREAD

**Issue by sunjunlishi** [davidweigao/AlexaSmartHome#2]
firstly ,in my skill,i find it and it work sccess.
Now how could i  get user's account name in python(amaza lambda)

**Comment by davidweigao** [comment]
which part are you asking? This project is for personal use so normally no usage for the user's account.

**Comment by sunjunlishi** [comment]
There is a skill service that someone can search for me. My service provides device management functions. Users can log on to my service page and register to add devices. When the user uses voice, I need to get the user's Alexa account, and I use this to find the user's corresponding device (i use lambda)

**Comment by davidweigao** [comment]
@sunjunlishi 
`additionalApplianceDetails` seems to be a good place to put user info, see [api spec](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference)

**Comment by sunjunlishi** [comment]
![qq 20170705103241](https://user-images.githubusercontent.com/11845664/27846996-7bdf216c-616d-11e7-80d5-5297cfc63882.png)

ok,thank for your help
